### PR TITLE
Use compiler output filesystem for stats.

### PR DESCRIPTION
**Pull request by izaakschroeder**
Instead of using node's `fs` make use of webpack's `outputFileSystem`. This is useful when using `webpack-dev-server` or similar where assets are served out of memory instead of on-disk. This also means that the async family of file system functions need to be used.

Instead of using the `done` event, use 'after-emit' which is async – there are ups and downs to this. It means that when consumers are listening for the `done` event then the stats file is guaranteed to be available, but also that the generated stats object is  (by default) missing some profiling information and timing. For the majority of people using this plugin to access the asset names this will not be a problem.

Use `mocha` and `chai` instead of `nodeunit` since `chai` has much better error reporting and it unfortunately doesn't seem to work well with `nodeunit`.

### CODE REVIEW

**Comment by izaakschroeder** [comment]
@sokra – Any way to have an async `before-done`? Or complete stats at `after-emit`?

**Comment by sokra** [comment]
You can try this in the `emit` hook:

``` js
compilation.assets["stats.json"] = {
  size: function() { return 0; }
  source: function() { return JSON.stringify(compilation.getStats().toJson()); }
};
```

This adds it to the assets array and let webpack handle the emitting.

**Comment by unindented** [comment]
@izaakschroeder Let me know if your PR needs changes after @sokra's comments. If not, I'll review and merge.

**Comment by izaakschroeder** [comment]
@unindented I will test it out later today and let you know :smile: thanks!

**Comment by izaakschroeder** [comment]
@unindented I tried out @sokra's suggestions and I think they work well! The only (possible) downside is that the output is now _always_ relative to webpack's output directory. This is kind of a breaking change since absolute paths now no longer work. Maybe @sokra has more :tophat: up his sleeve to address this? In either case still an improvement I think.

**Comment by sokra** [comment]
> Maybe @sokra has more  up his sleeve to address this?

We could add support for absolute paths for assets. This shouldn't be a big change...

**Comment by izaakschroeder** [comment]
Works for me! :tada:

**Comment by unindented** [comment]
@izaakschroeder The only thing I've found while reviewing is that `clone` is no longer needed in the test file, so we could delete that line, and also the `lodash` dependency, right?

Also, would it be too much to ask from you to run `jshint` and `jscs`, and fix the linting and styling issues? It looks like there's a mixture of 2-space and 4-space indentation, missing semicolons, etc.

**Comment by izaakschroeder** [comment]
Can do!

**Comment by izaakschroeder** [comment]
It's so shiny now! :gem: 

Linting has been added as part of CI too!

**Comment by unindented** [comment]
Wow, you've gone the extra mile. Thank you!

**Comment by izaakschroeder** [comment]
:smile:

**Comment by unindented** [comment]
Pushed `v0.2.0` of the package with your changes to npm. It's working fine with my projects, but please check it out.

**Comment by izaakschroeder** [comment]
Looks good from over here! The only possible issue I'm seeing in my output is:

```
stats.json  0 bytes          [emitted]
```

It says 0 bytes but it's lying: it's definitely not empty. I think maybe we patch up the `size()` call. However I'm not sure when either is called – the safest bet would be to have some kind of tmp var that keeps track of the size.

```javascript
var size = 0;
{
  source: function() { var res = ...; size = res.length; return res; },
  size: function() { return size; }
}
```

I don't know if the stats call has to be made inside the source (I assume so). This hack might not even work. Not really a big deal, the functionality is all there.

:+1: from me though.

**Comment by Coobaha** [comment]
@unindented with this changes destination folder is always relative to output, absolute path is created relative to build  output folder.

So if i want to move it outside from build, no i can only do something like '../stats.json', kinda strange imo.

**Comment by izaakschroeder** [comment]
This is kind of a missing feature in webpack! @sokra is working on it I think. It is annoying though, I agree. It was discussed somewhat above. :smile:

**Comment by Coobaha** [comment]
also, it breaks karma webpack plugin, i have to remove it from config if it is required in tests env :\

**Comment by izaakschroeder** [comment]
Just pin to `^0.1` for now if you need to.

**Comment by Coobaha** [comment]
yeap :)  this is just a report :)

**Comment by izaakschroeder** [comment]
:smile:

**Pull request merged**
