### PR TITLE
add webpack 3 support

### PR DESCRIPTION
**Pull request by modosc**
also updated other deps.

### CODE REVIEW

**Comment by ohadlevy** [comment]
:+1:

**Comment by ohadlevy** [comment]
bump? any chance to merge and release a new version of this package? thanks.

**Comment by jsg2021** [comment]
I moved on to [webpack-stats-plugin](https://github.com/FormidableLabs/webpack-stats-plugin) It doesn't specify peerDeps, and allows you transform the stats before writting it out.

**Comment by wilbert-abreu** [comment]
Please merge this as soon as possible, I'm not able to npm shrinkwrap due to this.

**Comment by cfeckardt** [comment]
Any news on this?

**Comment by lyushenko** [comment]
Could you merge this, please?

**Comment by cfeckardt** [comment]
Is this project abandoned?

**Comment by chrisui** [comment]
In case people need an alternative solution here I am using [webpack-bundle-analyzer](https://github.com/th0r/webpack-bundle-analyzer/) with `generateStatsFile` set to `true`.

**Comment by unindented** [comment]
Fixed in `v0.6.2`.

**Pull request closed without merging**
